### ISSUE TITLE
[Bug report] NameError: name 'add_units_isotherm' is not defined

### ISSUE THREAD

**Issue by Jules-Le** [modsim/CADET-Match#11]
Observation:
Error occurs:
 'File "C:\Users\jdiedric\AppData\Local\Continuum\anaconda3\lib\site-packages\CADETMatch\cache.py", line 447, in setupExperiment
    add_units_isotherm(units_used, feature['unit_name'])
NameError: name 'add_units_isotherm' is not defined' while doing fractionation parameter estimation in version 0.4.19.

Desired:
No error occurs.

Solution:
Fix bug by changing line 447 in cache.py from add_units_isotherm(units_used, feature['unit_name']) to self.add_units_isotherm(units_used, feature['unit_name'])

**Comment by Immudzen** [comment]
This is fixed in the current version of the code.
