### ISSUE TITLE
scoop import error

### ISSUE THREAD

**Issue by ronald-jaepel** [modsim/CADET-Match#12]
Environment: 
Ubuntu 16.04
fresh Conda Env created with just the anaconda bundle
(conda create -n CADETMatchEnv anaconda)
from within the env:
pip install CADETMatch

then during the first call to CADETMatch --match got this error:
[...]
2020-01-15 17:21:39,593 loggerwriter.py write 9   File "/home/scan/anaconda3/envs/CADETMatchEnv/lib/python3.7/site-packages/CADETMatch/scores/fractionationCombine.py", line 5, in <module>

2020-01-15 17:21:39,593 loggerwriter.py write 9     
2020-01-15 17:21:39,593 loggerwriter.py write 9 import scoop
2020-01-15 17:21:39,593 loggerwriter.py write 9 ModuleNotFoundError
2020-01-15 17:21:39,593 loggerwriter.py write 9 : 
2020-01-15 17:21:39,593 loggerwriter.py write 9 No module named 'scoop'

Appended full transcript. 
[conda_scoop_error.log](https://github.com/modsim/CADET-Match/files/4066042/conda_scoop_error.log)

Same installation procedure on windows 30 minutes earlier did not produce this error.

**Comment by Immudzen** [comment]
This is really strange. Scoop was removed on December 9th and that score being used there was moved into the retired folder before that. 
The current version is 0.5.16 and that one would have had to come before 0.5.2

Do you know what version pip installed?

**Comment by ronald-jaepel** [comment]
Here's what pip reported: 

Collecting CADETMatch
  Downloading https://files.pythonhosted.org/packages/d3/55/38440264b6732ef11269e6620b81dea104907bf2efdee64613ef18ef0125/CADETMatch-0.5.16-py3-none-any.whl (191kB)

All scores were in the scores folder, the retired folder doesn't exist when I check anaconda3/envs/CADETMatchEnv/lib/python3.7/site-packages/CADETMatch/scores

**Comment by Immudzen** [comment]
Uninstall CADETMatch and then go into the filesystem and verify that CADETMatch is actually uninstalled. The version you downloaded is the latest version but fractionationCombine should not be there and that makes me wonder if there is some kind of overlapping install.

**Comment by Immudzen** [comment]
This was most likely caused by the problem with building the wheel file which has been fixed.
