### ISSUE TITLE
score.pearson_spline results change when run repeatedly

### ISSUE THREAD

**Issue by ronald-jaepel** [modsim/CADET-Match#4]
Basically what the title says. With the current code, when going into debug mode and then re-running the line that computes the time offset using the pearson_spline returns different time-offsets. 

pearson, diff_time = score.pearson_spline(exp_time_values, sim_data_zero, exp_data_zero)

**Comment by ronald-jaepel** [comment]
Basically my question is: can you replicate this behavior or is one of those weird local bugs?

**Comment by Immudzen** [comment]
How large of a time difference do you see? In the tests I have run so far
it is never exactly the same offset but it is very close.

The system uses a genetic algorithm to find the time difference and that is
non-deterministic but experiments with a gradient descent involved the
gradient algorithm getting consistently stuck.

**Comment by ronald-jaepel** [comment]
it used to be ranging from -5 to 100 earlier this morning but right now as I'm trying to prepare data for you to replicate it on it doesn't differ by more than 0.01 or ~1%.

I'll give further feedback if I can replicate my own bug :D

**Comment by ronald-jaepel** [comment]
I can't replicate it. I don't know what was going on this morning.

**Comment by Immudzen** [comment]
I have seen weird things happen with these algorithms and then not able to
replicate before. This just seems to be something that happens when using
non-deterministic and complex systems.
