### ISSUE TITLE
[Feature request] Enabling parameter estimation for system parameters

### ISSUE THREAD

**Issue by Jules-Le** [modsim/CADET-Match#7]
Status:
Parameters that define the structural properties of the model are not subject to estimation. This is the case for section times, section number, discretization etc.

Desired:
Parameters that define the model structure are subject to estimation

Solution:
Enable discretization level for parameter estimation.

**Comment by Immudzen** [comment]
You can already do this. The optimizer does not know the difference between discretization variables and any other variable. Same with section times. I am not sure what it would mean from a practical level to do this if you wanted to match to experimental or synthetic data and you change the discretization and diffusion at the same time for instance but the optimizer itself should already allow this just fine.
