### ISSUE TITLE
[Feature request] written documentation regarding output files of optimizer

### ISSUE THREAD

**Issue by Jules-Le** [modsim/CADET-Match#9]
Status:
No documentation about the optimizer output files

Desired:
Written documentation about optimizer output files (meaning, what is plotted, etc.)

**Comment by schmoelder** [comment]
Hi, we have (finally) published the documentation: https://cadet.github.io/CADET-Match/master/index.html

**Comment by Jules-Le** [comment]
Cool, thanks Johannes!
